# Build settings
highlighter: pygments

# Site settings
title: "Kiwano"
description: > # this means to ignore newlines until "email:"
   Harvest the fruit of the crypto tree, to spread abundance in the world

email: emmanuel.calvet@usherbrooke.ca
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Kiwano'
author: 'Kiwano Boys'
author_image: "/assets/images/kiwano.jpg"

paginate:	5


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://github.com/onekiwano/onekiwano.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!

#permalink: /:title/

# The release of Jekyll Now that you're using
#version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
kramdown:
  #math_engine: mathjax
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

disqus:
 shortname: https-github-io-kiwano # Here's where you put your unique shortname

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


# social icons and sharing options
#social:
#  - icon:  github
#    url: https://github.com/Kiwano
#    desc:  Fork me on github
    #share_url: https://github.com/Kiwano?tab=repositories
    #share_title: ?text="My repo"
    #share_link: "&amp;url="

#  - icon:	twitter
#    url:	https://twitter.com/samyonski
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/samyonski
#    desc: Connect with me on facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="



#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
